################################################################################
# pyinstaller.yaml
#
# Compile the executable using PyInstaller via the main.spec file on Windows,
# macOS, and Linux.
################################################################################

name: PyInstaller build

on:
  push:
    paths:
      - "**/*.py"
      - ".github/workflows/pyinstaller.yaml"
    branches:
      - main
  pull_request:
    paths:
      - "**/*.py"
      - ".github/workflows/pyinstaller.yaml"
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}  # Use the matrix to define the target OS.

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]  # Supported OSes.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      # Required for use of Kivy
      - name: Install MTDev on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libmtdev-dev libmtdev1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run PyInstaller main.spec
        run: |
          pyinstaller --clean --noconfirm main.py
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/*
